// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxrLRBS11WPqBz3VLT1OalhICe1eMc5g',
    appId: '1:348089596709:web:064ed72db3935519f338cc',
    messagingSenderId: '348089596709',
    projectId: 'code-test-ajaya',
    authDomain: 'code-test-ajaya.firebaseapp.com',
    storageBucket: 'code-test-ajaya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6amGLUGH_Xugmyh_MaGZvPaNfbeOnI5s',
    appId: '1:348089596709:android:3662a2ba7470f166f338cc',
    messagingSenderId: '348089596709',
    projectId: 'code-test-ajaya',
    storageBucket: 'code-test-ajaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMq4-nPh4I15FQuwJQVer1O2C6v3-khKA',
    appId: '1:348089596709:ios:bbfa794f459dc04ef338cc',
    messagingSenderId: '348089596709',
    projectId: 'code-test-ajaya',
    storageBucket: 'code-test-ajaya.appspot.com',
    iosBundleId: 'com.example.codeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMq4-nPh4I15FQuwJQVer1O2C6v3-khKA',
    appId: '1:348089596709:ios:bbfa794f459dc04ef338cc',
    messagingSenderId: '348089596709',
    projectId: 'code-test-ajaya',
    storageBucket: 'code-test-ajaya.appspot.com',
    iosBundleId: 'com.example.codeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxrLRBS11WPqBz3VLT1OalhICe1eMc5g',
    appId: '1:348089596709:web:3d59a2bf7418b1adf338cc',
    messagingSenderId: '348089596709',
    projectId: 'code-test-ajaya',
    authDomain: 'code-test-ajaya.firebaseapp.com',
    storageBucket: 'code-test-ajaya.appspot.com',
  );
}
